import { JobListing } from ".";

export const mockJobListings: JobListing[] = [
  {
    job_id: '101',
    experience: '2 to 5 Years',
    qualifications: 'B.Sc Computer Science',
    salary_range: '$50K-$70K',
    location: 'New York',
    country: 'USA',
    latitude: 40.7128,
    longitude: -74.006,
    work_type: 'Fulltime',
    company_size: 150,
    job_posting_date: '2023-11-01',
    preference: 'Any',
    contact_person: 'Alice Johnson',
    contact: 'alice.johnson@example.com',
    job_title: 'Frontend Developer',
    role: 'Software Engineer',
    job_portal: 'LinkedIn',
    job_description: 'Develop user interfaces for web applications using React.',
    benefits: ['Health insurance', 'Remote work', '401(k)'],
    skills: ['JavaScript', 'React', 'CSS', 'HTML'],
    responsibilities: [
      'Build and maintain UI components',
      'Collaborate with design and backend teams',
      'Optimize application performance'
    ],
    company: 'Tech Solutions Inc',
    company_profile: {
      CEO: 'John Smith',
      Zip: '10001',
      City: 'New York',
      State: 'NY',
      Sector: 'Technology',
      Ticker: 'TSI',
      Website: 'www.techsolutions.com',
      Industry: 'Software Development'
    }
  },
  {
    job_id: '102',
    experience: '3 to 7 Years',
    qualifications: 'M.Sc Data Science',
    salary_range: '$80K-$110K',
    location: 'San Francisco',
    country: 'USA',
    latitude: 37.7749,
    longitude: -122.4194,
    work_type: 'Fulltime',
    company_size: 500,
    job_posting_date: '2023-10-20',
    preference: 'Any',
    contact_person: 'Bob Williams',
    contact: 'bob.williams@example.com',
    job_title: 'Data Scientist',
    role: 'Data Analyst',
    job_portal: 'Glassdoor',
    job_description: 'Analyze data trends and build predictive models.',
    benefits: ['Stock options', 'Gym membership', 'Health insurance'],
    skills: ['Python', 'Machine Learning', 'SQL', 'Statistics'],
    responsibilities: [
      'Collect and analyze large datasets',
      'Develop machine learning models',
      'Present insights to stakeholders'
    ],
    company: 'DataX Analytics',
    company_profile: {
      CEO: 'Linda Green',
      Zip: '94103',
      City: 'San Francisco',
      State: 'CA',
      Sector: 'Analytics',
      Ticker: 'DXA',
      Website: 'www.dataxanalytics.com',
      Industry: 'Data Science'
    }
  },
  {
    job_id: '103',
    experience: '1 to 3 Years',
    qualifications: 'B.Eng Mechanical',
    salary_range: '$60K-$80K',
    location: 'Chicago',
    country: 'USA',
    latitude: 41.8781,
    longitude: -87.6298,
    work_type: 'Contract',
    company_size: 200,
    job_posting_date: '2023-10-15',
    preference: 'Male',
    contact_person: 'Carol Martinez',
    contact: 'carol.martinez@example.com',
    job_title: 'Mechanical Engineer',
    role: 'Design Engineer',
    job_portal: 'Indeed',
    job_description: 'Design mechanical components and systems for automotive applications.',
    benefits: ['Health insurance', 'Paid time off', 'Travel allowance'],
    skills: ['CAD', 'SolidWorks', 'Thermodynamics', 'Project management'],
    responsibilities: [
      'Design mechanical parts',
      'Conduct stress analysis',
      'Coordinate with manufacturing'
    ],
    company: 'AutoTech Corp',
    company_profile: {
      CEO: 'Mike Thompson',
      Zip: '60601',
      City: 'Chicago',
      State: 'IL',
      Sector: 'Automotive',
      Ticker: 'ATC',
      Website: 'www.autotechcorp.com',
      Industry: 'Automotive Manufacturing'
    }
  },
  {
    job_id: '104',
    experience: '5 to 10 Years',
    qualifications: 'MBA',
    salary_range: '$90K-$130K',
    location: 'London',
    country: 'UK',
    latitude: 51.5074,
    longitude: -0.1278,
    work_type: 'Fulltime',
    company_size: 1000,
    job_posting_date: '2023-09-30',
    preference: 'Any',
    contact_person: 'David Brown',
    contact: 'david.brown@example.co.uk',
    job_title: 'Product Manager',
    role: 'Product Owner',
    job_portal: 'LinkedIn',
    job_description: 'Lead product development and coordinate cross-functional teams.',
    benefits: ['Health insurance', 'Stock options', 'Flexible hours'],
    skills: ['Agile', 'Scrum', 'Leadership', 'Communication'],
    responsibilities: [
      'Define product roadmap',
      'Work with engineering teams',
      'Gather and prioritize requirements'
    ],
    company: 'Innovatech Ltd',
    company_profile: {
      CEO: 'Emma Wilson',
      Zip: 'EC1A 1BB',
      City: 'London',
      State: 'Greater London',
      Sector: 'Technology',
      Ticker: 'ITL',
      Website: 'www.innovatech.co.uk',
      Industry: 'Information Technology'
    }
  },
  {
    job_id: '105',
    experience: '2 to 4 Years',
    qualifications: 'B.A Marketing',
    salary_range: '$45K-$60K',
    location: 'Toronto',
    country: 'Canada',
    latitude: 43.6532,
    longitude: -79.3832,
    work_type: 'Fulltime',
    company_size: 120,
    job_posting_date: '2023-10-05',
    preference: 'Any',
    contact_person: 'Emma Lee',
    contact: 'emma.lee@example.ca',
    job_title: 'Marketing Specialist',
    role: 'Marketing',
    job_portal: 'Indeed',
    job_description: 'Plan and execute marketing campaigns to increase brand awareness.',
    benefits: ['Health benefits', 'Paid time off', 'Professional development'],
    skills: ['SEO', 'Content marketing', 'Social media', 'Google Analytics'],
    responsibilities: [
      'Develop marketing strategies',
      'Manage social media channels',
      'Analyze campaign performance'
    ],
    company: 'MarketPro Inc',
    company_profile: {
      CEO: 'Oliver King',
      Zip: 'M5H 2N2',
      City: 'Toronto',
      State: 'ON',
      Sector: 'Marketing',
      Ticker: 'MPI',
      Website: 'www.marketpro.com',
      Industry: 'Marketing & Advertising'
    }
  },
  {
    job_id: '106',
    experience: '3 to 6 Years',
    qualifications: 'B.Sc Finance',
    salary_range: '$70K-$90K',
    location: 'Sydney',
    country: 'Australia',
    latitude: -33.8688,
    longitude: 151.2093,
    work_type: 'Fulltime',
    company_size: 350,
    job_posting_date: '2023-11-10',
    preference: 'Any',
    contact_person: 'George Smith',
    contact: 'george.smith@example.au',
    job_title: 'Financial Analyst',
    role: 'Finance',
    job_portal: 'LinkedIn',
    job_description: 'Analyze financial data and assist in budgeting and forecasting.',
    benefits: ['Health insurance', 'Bonus', 'Retirement plan'],
    skills: ['Excel', 'Financial modeling', 'Data analysis', 'Communication'],
    responsibilities: [
      'Prepare financial reports',
      'Analyze market trends',
      'Support budgeting processes'
    ],
    company: 'FinCorp Pty Ltd',
    company_profile: {
      CEO: 'Samantha Wilson',
      Zip: '2000',
      City: 'Sydney',
      State: 'NSW',
      Sector: 'Finance',
      Ticker: 'FCP',
      Website: 'www.fincorp.com.au',
      Industry: 'Financial Services'
    }
  },
  {
    job_id: '107',
    experience: '1 to 2 Years',
    qualifications: 'B.Sc Biology',
    salary_range: '$40K-$55K',
    location: 'Berlin',
    country: 'Germany',
    latitude: 52.52,
    longitude: 13.405,
    work_type: 'Temporary',
    company_size: 80,
    job_posting_date: '2023-10-12',
    preference: 'Any',
    contact_person: 'Lisa Müller',
    contact: 'lisa.mueller@example.de',
    job_title: 'Lab Technician',
    role: 'Research',
    job_portal: 'StepStone',
    job_description: 'Support research activities and perform lab tests.',
    benefits: ['Paid vacation', 'Training programs'],
    skills: ['Laboratory skills', 'Data recording', 'Attention to detail'],
    responsibilities: [
      'Prepare lab samples',
      'Maintain lab equipment',
      'Record experiment results'
    ],
    company: 'BioLabs GmbH',
    company_profile: {
      CEO: 'Klaus Schmidt',
      Zip: '10115',
      City: 'Berlin',
      State: 'Berlin',
      Sector: 'Biotechnology',
      Ticker: 'BLG',
      Website: 'www.biolabs.de',
      Industry: 'Biotech Research'
    }
  },
  {
    job_id: '108',
    experience: '4 to 8 Years',
    qualifications: 'B.Eng Civil',
    salary_range: '$75K-$95K',
    location: 'Mumbai',
    country: 'India',
    latitude: 19.076,
    longitude: 72.8777,
    work_type: 'Fulltime',
    company_size: 600,
    job_posting_date: '2023-10-25',
    preference: 'Any',
    contact_person: 'Ankit Mehra',
    contact: 'ankit.mehra@example.in',
    job_title: 'Civil Engineer',
    role: 'Engineering',
    job_portal: 'Naukri',
    job_description: 'Plan and supervise construction projects.',
    benefits: ['Health insurance', 'Commuter allowance', 'Bonuses'],
    skills: ['AutoCAD', 'Project management', 'Structural analysis'],
    responsibilities: [
    'Manage construction sites',
    'Coordinate with architects and contractors',
    'Ensure safety compliance'
    ],
    company: 'BuildRight Pvt Ltd',
    company_profile: {
        CEO: 'Ravi Kapoor',
        Zip: '400001',
        City: 'Mumbai',
        State: 'Maharashtra',
        Sector: 'Construction',
        Ticker: 'BRPL',
        Website: 'www.buildright.in',
        Industry: 'Civil Engineering'
    }
},
{
    job_id: '109',
    experience: '3 to 5 Years',
    qualifications: 'B.A Graphic Design',
    salary_range: '$55K-$75K',
    location: 'Paris',
    country: 'France',
    latitude: 48.8566,
    longitude: 2.3522,
    work_type: 'Remote',
    company_size: 90,
    job_posting_date: '2023-11-05',
    preference: 'Any',
    contact_person: 'Chloé Laurent',
    contact: 'chloe.laurent@example.fr',
    job_title: 'UI/UX Designer',
    role: 'Design',
    job_portal: 'Welcome to the Jungle',
    job_description: 'Design user-friendly interfaces and improve user experiences.',
    benefits: ['Remote work', 'Annual bonus', 'Work equipment'],
    skills: ['Figma', 'Adobe XD', 'Wireframing', 'User research'],
    responsibilities: [
    'Create wireframes and mockups',
    'Conduct user testing',
    'Collaborate with developers'
    ],
    company: 'PixelCraft SAS',
    company_profile: {
        CEO: 'Jean Dupont',
        Zip: '75001',
        City: 'Paris',
        State: 'Île-de-France',
        Sector: 'Design',
        Ticker: 'PCS',
        Website: 'www.pixelcraft.fr',
        Industry: 'Creative Design'
    }
},
{
    job_id: '110',
    experience: '0 to 1 Year',
    qualifications: 'B.Sc Computer Science',
    salary_range: '$30K-$40K',
    location: 'Jakarta',
    country: 'Indonesia',
    latitude: -6.2088,
    longitude: 106.8456,
    work_type: 'Internship',
    company_size: 60,
    job_posting_date: '2023-11-15',
    preference: 'Any',
    contact_person: 'Nadia Rahma',
    contact: 'nadia.rahma@example.id',
    job_title: 'Software Engineer Intern',
    role: 'Internship',
    job_portal: 'Kalibrr',
    job_description: 'Assist in developing backend services and APIs.',
    benefits: ['Mentorship', 'Flexible hours', 'Internship allowance'],
    skills: ['Python', 'Django', 'REST API', 'SQL'],
    responsibilities: [
    'Write clean backend code',
    'Fix bugs and test features',
    'Participate in daily standups'
    ],
    company: 'Codeverse ID',
    company_profile: {
        CEO: 'Aditya Santoso',
        Zip: '10210',
        City: 'Jakarta',
        State: 'DKI Jakarta',
        Sector: 'Technology',
        Ticker: 'CVID',
        Website: 'www.codeverse.id',
        Industry: 'Software Development'
    }
  }
];