name: Deploy Next.js to GCP VM

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-ir:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-ir:latest

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.VM_SSH_KEY }}

    - name: Deploy to GCP VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-ir:latest
          docker stop frontend-ir || true
          docker rm frontend-ir || true
          docker run -d --name frontend-ir -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/frontend-ir:latest
        EOF
